/* This file is autogenerated by classes.UP. Do not edit!

    Copyright (c) 2010 - 2015, All Rights Reserved
    The authors are listed in the AUTHORS file.

    ROOT dictionary that Kappa uses for reading the Kappa skim

	http://root.cern.ch/drupal/content/selecting-dictionary-entries-linkdefh
	http://root.cern.ch/drupal/content/interacting-shared-libraries-rootcint
*/

#ifndef KDATAFORMAT_CLASSES_H
#define KDATAFORMAT_CLASSES_H

#define G__DICTIONARY

#include "../interface/KBasic.h"
#include "../interface/KElectron.h"
#include "../interface/KInfo.h"
#include "../interface/KJetMET.h"
#include "../interface/KLepton.h"
#include "../interface/KMuon.h"
#include "../interface/KParticle.h"
#include "../interface/KRoot.h"
#include "../interface/KTau.h"
#include "../interface/KTrack.h"

namespace
{
	struct dictionary
	{
		RMFLV dict_RMFLV;
		RMFLV_Store dict_RMFLV_Store;
		RMDLV dict_RMDLV;
		RMDLV_Store dict_RMDLV_Store;
		KEventInfo dict_KEventInfo;
		KGenEventInfo dict_KGenEventInfo;
		KBasicJet dict_KBasicJet;
		KBasicJets dict_KBasicJets;
		KBasicMET dict_KBasicMET;
		KBasicTau dict_KBasicTau;
		KBasicTaus dict_KBasicTaus;
		KBeamSpot dict_KBeamSpot;
		KBeamSpots dict_KBeamSpots;
		KCaloJet dict_KCaloJet;
		KCaloJets dict_KCaloJets;
		KElectron dict_KElectron;
		KElectrons dict_KElectrons;
		KLV dict_KLV;
		KLVs dict_KLVs;
		KGenJet dict_KGenJet;
		KGenJets dict_KGenJets;
		KGenParticle dict_KGenParticle;
		KGenParticles dict_KGenParticles;
		KGenPhoton dict_KGenPhoton;
		KGenPhotons dict_KGenPhotons;
		KGenTau dict_KGenTau;
		KGenTaus dict_KGenTaus;
		KHit dict_KHit;
		KHits dict_KHits;
		KJet dict_KJet;
		KJets dict_KJets;
		KL1Muon dict_KL1Muon;
		KL1Muons dict_KL1Muons;
		KLepton dict_KLepton;
		KLeptons dict_KLeptons;
		KMET dict_KMET;
		KMuon dict_KMuon;
		KMuons dict_KMuons;
		KMuonTriggerCandidate dict_KMuonTriggerCandidate;
		KMuonTriggerCandidates dict_KMuonTriggerCandidates;
		KParticle dict_KParticle;
		KParticles dict_KParticles;
		KPFCandidate dict_KPFCandidate;
		KPFCandidates dict_KPFCandidates;
		KPileupDensity dict_KPileupDensity;
		KTau dict_KTau;
		KTaus dict_KTaus;
		KExtendedTau dict_KExtendedTau;
		KExtendedTaus dict_KExtendedTaus;
		KTaupairVerticesMap dict_KTaupairVerticesMap;
		KTaupairVerticesMaps dict_KTaupairVerticesMaps;
		KTrack dict_KTrack;
		KTracks dict_KTracks;
		KTrackPair dict_KTrackPair;
		KTrackPairs dict_KTrackPairs;
		KTriggerObjects dict_KTriggerObjects;
		KVertex dict_KVertex;
		KVertices dict_KVertices;
		KFilterSummary dict_KFilterSummary;
		KHCALNoiseSummary dict_KHCALNoiseSummary;
		KTrackSummary dict_KTrackSummary;
		KVertexSummary dict_KVertexSummary;
		KLumiInfo dict_KLumiInfo;
		KGenLumiInfo dict_KGenLumiInfo;
		KDataLumiInfo dict_KDataLumiInfo;
		KElectronMetadata dict_KElectronMetadata;
		KFilterMetadata dict_KFilterMetadata;
		KMuonMetadata dict_KMuonMetadata;
		KJetMetadata dict_KJetMetadata;
		KTauMetadata dict_KTauMetadata;
		KTriggerObjectMetadata dict_KTriggerObjectMetadata;
		KProvenance dict_KProvenance;
	};
}

#endif
