/* This file is autogenerated by classes.UP. Do not edit!

    Copyright (c) 2010 - 2015, All Rights Reserved
    The authors are listed in the AUTHORS file.

    Standalone script to test the debug outputs of Kappa

    compile with
    g++ testDebug.cc $(root-config --cflags) $(root-config --ldflags --libs) -I../.. -o testdebug  -L../../lib -lKappa -lGenVector
*/

#include "DataFormats/interface/KDebug.h"
#include <iostream>

using namespace std;

int main() {
	cout << "Kappa object debug output:" << endl;
	cout << "* KEventInfo: " << KEventInfo() << endl;
	cout << "* KGenEventInfo: " << KGenEventInfo() << endl;
	cout << "* KBasicJet: " << KBasicJet() << endl;
	cout << "* KBasicMET: " << KBasicMET() << endl;
	cout << "* KBasicTau: " << KBasicTau() << endl;
	cout << "* KBeamSpot: " << KBeamSpot() << endl;
	cout << "* KCaloJet: " << KCaloJet() << endl;
	cout << "* KElectron: " << KElectron() << endl;
	cout << "* KLV: " << KLV() << endl;
	cout << "* KGenParticle: " << KGenParticle() << endl;
	cout << "* KGenTau: " << KGenTau() << endl;
	cout << "* KHit: " << KHit() << endl;
	cout << "* KJet: " << KJet() << endl;
	cout << "* KMET: " << KMET() << endl;
	cout << "* KPFCandidate: " << KPFCandidate() << endl;
	cout << "* KPileupDensity: " << KPileupDensity() << endl;
	cout << "* KTaupairVerticesMap: " << KTaupairVerticesMap() << endl;
	cout << "* KVertex: " << KVertex() << endl;
	cout << "* KFilterSummary: " << KFilterSummary() << endl;
	cout << "* KTrackSummary: " << KTrackSummary() << endl;
	cout << "* KVertexSummary: " << KVertexSummary() << endl;
	cout << "* KLumiInfo: " << KLumiInfo() << endl;
	cout << "* KGenLumiInfo: " << KGenLumiInfo() << endl;
	cout << "* KDataLumiInfo: " << KDataLumiInfo() << endl;
	cout << "* KMuonMetadata: " << KMuonMetadata() << endl;
	cout << "* KTauMetadata: " << KTauMetadata() << endl;
	cout << "* KProvenance: " << KProvenance() << endl;
}
